### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by dasayan05** [crystalcpp/tensorpp#2]
## First phase of the project, so require basic stuffs to be done
- [ ] no need for separate versioning module, we can have a general `utils` module which will contain versioning utility
- [ ] create convenient wrapper around `cxxopts`
- [ ] create convenient wrapper around `spdlog`
- [ ] make a uniform MACRO style
- [ ] add BLAS as dependency

**Comment by dasayan05** [comment]
@DarkStar1997 The last entry in the list is for you to do.
